"use client"

import { useState } from "react"
import { ArrowUpRight, ChevronDown, LockKeyhole, Menu, ShieldCheck, X, Zap } from "lucide-react"
import { LiquidBackground } from "@/components/liquid-background"

const roles = [
  { title: "For finance teams", copy: "Run payroll, invoices, and treasury operations without exposing sensitive counterparties.", icon: ShieldCheck },
  { title: "For contributors", copy: "Get paid globally with a clean, private payment experience built for modern work.", icon: Zap },
  { title: "For compliance", copy: "Prove what matters without putting your entire financial graph on display.", icon: LockKeyhole },
]

function Logo() {
  return <span className="flex items-center gap-3" aria-label="PrivyPay home"><span className="grid size-9 place-items-center rounded-xl border border-primary/40 bg-primary/15 text-primary shadow-lg shadow-primary/10" aria-hidden="true"><svg viewBox="0 0 32 32" className="size-5" fill="none"><path d="M16 3.5 27.5 10v12L16 28.5 4.5 22V10L16 3.5Z" stroke="currentColor" strokeWidth="1.75"/><path d="m10 16 4 4 8-9" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"/></svg></span><span className="font-mono text-sm font-semibold tracking-[0.28em]">PRIVYPAY</span></span>
}

export default function WaitlistHero() {
  const [mobileOpen, setMobileOpen] = useState(false)



  return <div className="liquid-surface relative min-h-screen overflow-hidden bg-background text-foreground">
    <LiquidBackground />
    <div className="pointer-events-none fixed inset-0 z-0 bg-[radial-gradient(circle_at_center,transparent_0%,rgba(4,7,18,0.2)_58%,rgba(4,7,18,0.72)_100%)]" />
    <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-6 py-6 lg:px-10">
      <a href="#top" aria-label="PrivyPay home"><Logo /></a>
      <nav className="hidden items-center gap-8 text-sm text-muted-foreground md:flex"><a href="#why" className="water-text transition-colors hover:text-foreground">Why private</a><a href="#product" className="water-text transition-colors hover:text-foreground">Product</a><a href="#trust" className="water-text transition-colors hover:text-foreground">Trust</a></nav>
      <a href="/wallet" className="hidden items-center gap-2 rounded-full border border-border/80 bg-card/50 px-4 py-2 text-sm font-medium backdrop-blur-md transition-colors hover:border-primary/60 md:flex">Launch app <ArrowUpRight className="size-4" /></a>
      <button className="rounded-lg border border-border/80 p-2 md:hidden" onClick={() => setMobileOpen((v) => !v)} aria-label="Toggle menu" aria-expanded={mobileOpen}>{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button>
    </header>
    {mobileOpen && <nav className="relative z-20 mx-6 flex flex-col gap-4 rounded-2xl border border-border/80 bg-card/90 p-5 text-sm backdrop-blur-xl md:hidden"><a href="#why" onClick={() => setMobileOpen(false)}>Why private</a><a href="#product" onClick={() => setMobileOpen(false)}>Product</a><a href="#trust" onClick={() => setMobileOpen(false)}>Trust</a></nav>}

    <main id="top" className="relative z-10">
      <section className="mx-auto grid max-w-7xl items-center gap-16 px-6 pb-24 pt-16 lg:grid-cols-[1.05fr_0.95fr] lg:px-10 lg:pb-36 lg:pt-24">
        <div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1.5 font-mono text-[11px] uppercase tracking-[0.2em] text-primary"><span className="size-1.5 rounded-full bg-accent" /> <span className="water-text">Confidential finance infrastructure</span></div><h1 className="max-w-3xl text-balance text-5xl font-medium leading-[1.03] tracking-[-0.06em] sm:text-7xl lg:text-[6.7rem]"><span className="water-text">Money moves better </span><span className="water-text font-serif italic text-primary">in private.</span></h1><p className="water-text mt-7 max-w-xl text-pretty text-base leading-7 text-muted-foreground sm:text-lg">PrivyPay is the confidential payroll and invoicing layer for teams that believe financial privacy is a feature, not a compromise.</p><a href="/wallet" className="mt-9 inline-flex h-12 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground transition hover:brightness-110">Open app <ArrowUpRight className="size-4" /></a></div>
        <div id="product" className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-8 rounded-[2rem] bg-primary/10 blur-3xl" /><div className="relative overflow-hidden rounded-[1.4rem] border border-border/80 bg-card/80 shadow-2xl shadow-primary/10 backdrop-blur-xl"><div className="flex items-center justify-between border-b border-border/70 px-5 py-4"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">PrivyPay console</p><p className="mt-1 text-sm font-medium">Treasury overview</p></div><div className="flex items-center gap-2 rounded-full bg-accent/10 px-2.5 py-1 text-[10px] text-accent"><span className="size-1.5 rounded-full bg-accent" /> Private mode</div></div><div className="grid gap-5 p-5 sm:p-7"><div className="rounded-xl border border-border/70 bg-background/50 p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">Available balance</p><p className="mt-2 text-3xl font-medium tracking-tight">$248,920<span className="text-base text-muted-foreground">.40</span></p></div><div className="rounded-lg bg-primary/10 p-2 text-primary"><LockKeyhole className="size-4" /></div></div><div className="mt-6 h-20"><svg viewBox="0 0 400 80" className="h-full w-full" role="img" aria-label="Balance trend"><path d="M0 63 C35 55 44 65 70 53 S105 42 125 49 S150 40 174 44 S205 28 232 35 S260 32 280 20 S315 37 335 26 S365 19 400 8" fill="none" stroke="currentColor" strokeWidth="2" className="text-primary"/><path d="M0 63 C35 55 44 65 70 53 S105 42 125 49 S150 40 174 44 S205 28 232 35 S260 32 280 20 S315 37 335 26 S365 19 400 8 V80 H0Z" className="fill-primary/10"/></svg></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border/70 bg-background/40 p-4"><div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">Next payroll</p><ChevronDown className="size-4 text-muted-foreground"/></div><p className="mt-4 text-lg font-medium">$86,240.00</p><p className="mt-1 text-xs text-accent">Encrypted until settlement</p></div><div className="rounded-xl border border-border/70 bg-background/40 p-4"><p className="text-xs text-muted-foreground">Counterparties</p><p className="mt-4 text-lg font-medium">24 private</p><p className="mt-1 text-xs text-muted-foreground">Zero exposed balances</p></div></div></div></div></div>
      </section>
      <section id="why" className="mx-auto max-w-7xl border-t border-border/60 px-6 py-20 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="water-text font-mono text-[11px] uppercase tracking-[0.2em] text-primary">A quieter ledger</p><h2 className="water-text mt-4 max-w-md text-4xl font-medium tracking-[-0.04em] sm:text-5xl">Privacy for the parts that matter.</h2></div><div className="grid gap-4 md:grid-cols-3">{roles.map((role) => { const Icon = role.icon; return <article key={role.title} className="rounded-2xl border border-border/70 bg-card/40 p-5 backdrop-blur-sm transition hover:-translate-y-1 hover:border-primary/50"><Icon className="size-5 text-primary"/><h3 className="water-text mt-8 font-medium">{role.title}</h3><p className="water-text mt-3 text-sm leading-6 text-muted-foreground">{role.copy}</p></article> })}</div></div></section>
      <section id="trust" className="mx-auto max-w-7xl px-6 pb-24 lg:px-10 lg:pb-32"><div className="flex flex-col justify-between gap-8 rounded-3xl border border-border/70 bg-card/40 p-7 backdrop-blur-md sm:p-10 md:flex-row md:items-end"><div><p className="water-text font-mono text-[11px] uppercase tracking-[0.2em] text-primary">Built for the real world</p><h2 className="water-text mt-4 max-w-2xl text-3xl font-medium tracking-[-0.04em] sm:text-4xl">The future of finance should feel calm, clear, and confidential.</h2></div><div className="flex flex-col gap-4"><div className="water-text flex max-w-xs items-center gap-3 text-sm leading-6 text-muted-foreground"><LockKeyhole className="size-5 shrink-0 text-accent"/> Powered by confidential tokens on Stellar. Infrastructure designed for responsible financial operations.</div><a href="/wallet" className="inline-flex w-fit items-center gap-2 rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground transition hover:brightness-110">Open app <ArrowUpRight className="size-4" /></a></div></div></section>
    </main>
    <footer className="relative z-10 mx-auto flex max-w-7xl flex-col gap-3 border-t border-border/60 px-6 py-7 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between lg:px-10"><span className="water-text font-mono tracking-[0.18em]">PRIVYPAY / PRIVATE MONEY INFRASTRUCTURE</span><div className="flex items-center gap-4"><a href="https://forms.gle/your-form-id" target="_blank" rel="noopener noreferrer" className="water-text hover:text-foreground transition-colors">Leave feedback</a><span className="water-text">© 2026 PrivyPay. Confidential by design.</span></div></footer>
  </div>
}
